@baseUrl = http://localhost:8080
@type = application/json

@kitchenEndpoint = /kitchen
@restaurantEndpoint = /restaurants
@stateEndpoint = /state

@stateId = 1
@cozinhaId = 1
@restaurantId = 1

### Cozinhas ###

### Criar cozinha

# @name Create Kitchen
POST {{baseUrl}}{{kitchenEndpoint}}
Accept: {{type}}
Content-Type: {{type}}

{
  "name": "Brasileira"
}

### Atualizar cozinha

# name Update Kitchen
PUT {{baseUrl}}{{kitchenEndpoint}}/{{cozinhaId}}
Accept: {{type}}
Content-Type: {{type}}

{
  "name": "Nome estranho"
}

### Deletar cozinha

# @name Delete Kitchen
DELETE {{baseUrl}}{{kitchenEndpoint}}/{{cozinhaId}}
Accept: {{type}}
Content-Type: {{type}}

### Restaurantes ###

### Listar todos os restaurantes

# @name List Restaurants
GET {{baseUrl}}{{restaurantEndpoint}}
Accept: {{type}}
Content-Type: {{type}}

### Buscar restaurante por id

# @name Get Restaurant by Id
GET {{baseUrl}}{{restaurantEndpoint}}/{{restaurantId}}
Accept: {{type}}
Content-Type: {{type}}

### Criar restaurante

# @name Create Restaurant
POST {{baseUrl}}{{restaurantEndpoint}}
Accept: {{type}}
Content-Type: {{type}}

{
   "name" : "new_restaurant",
   "kitchen": {
    "id" : 1
   },
   "tax_fee" : 1,
   "is_open" : true,
   "is_active" : true
}

### Atualizar restaurante parcialmente

# @name Partial restaurant update
PATCH {{baseUrl}}{{restaurantEndpoint}}/{{restaurantId}}
Accept: {{type}}
Content-Type: {{type}}

{
   "name" : "new_name"
}

### Deletar estado

# @name Delete State
DELETE {{baseUrl}}{{stateEndpoint}}/{{stateId}}
Accept: {{type}}
Content-Type: {{type}}