@baseUrl = http://localhost:8080
@type = application/json

@kitchenEndpoint = /kitchen
@cozinhaId = 1

### Criar nova Cozinha

POST {{baseUrl}}{{kitchenEndpoint}}
Accept: {{type}}
Content-Type: {{type}}

{
  "name": "Brasileira"
}

### Atualizar cozinha

PUT {{baseUrl}}{{kitchenEndpoint}}/{{cozinhaId}}
Accept: {{type}}
Content-Type: {{type}}

{
  "name": "Nome estranho"
}

### Deletar cozinha

DELETE {{baseUrl}}{{kitchenEndpoint}}/{{cozinhaId}}
Accept: {{type}}
Content-Type: {{type}}